import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FitLogProvider } from "@/context/FitLogContext";
import Navbar from "@/components/Navbar/page";
import Banner from "@/components/Banner/page"

import { Oswald } from "next/font/google";

// ১. Oswald ফন্টের জন্য ভ্যারিয়েবল এবং ওজন (weights) ডিক্লেয়ার করা হলো
const oswald = Oswald({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-oswald",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FITLOG",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      // ২. className-এ oswald.variable যোগ করা হলো
      className={`${geistSans.variable} ${geistMono.variable} ${oswald.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <FitLogProvider>
        <Navbar />
        <Banner />
        {children}
        </FitLogProvider>

      </body>
    </html>
  );
}